// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE5Ro61g73o6pWeOI-J3Lr8hPId9qoZIE',
    appId: '1:130994604981:web:7d1f049871d2c33fc4a7fc',
    messagingSenderId: '130994604981',
    projectId: 'tv-ads-bf45e',
    authDomain: 'tv-ads-bf45e.firebaseapp.com',
    storageBucket: 'tv-ads-bf45e.appspot.com',
    measurementId: 'G-4H67SZ81ZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf3zQbH6BtY80kgv4l-ij-AW6Grh9uIwg',
    appId: '1:130994604981:android:8c2ff313d6c0972cc4a7fc',
    messagingSenderId: '130994604981',
    projectId: 'tv-ads-bf45e',
    storageBucket: 'tv-ads-bf45e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrixmBPzrACB5wo1z3lxbIf6O0TjMnejU',
    appId: '1:130994604981:ios:4470b6e8ddc95afbc4a7fc',
    messagingSenderId: '130994604981',
    projectId: 'tv-ads-bf45e',
    storageBucket: 'tv-ads-bf45e.appspot.com',
    iosBundleId: 'com.ashmawi.tvAds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrixmBPzrACB5wo1z3lxbIf6O0TjMnejU',
    appId: '1:130994604981:ios:4470b6e8ddc95afbc4a7fc',
    messagingSenderId: '130994604981',
    projectId: 'tv-ads-bf45e',
    storageBucket: 'tv-ads-bf45e.appspot.com',
    iosBundleId: 'com.ashmawi.tvAds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE5Ro61g73o6pWeOI-J3Lr8hPId9qoZIE',
    appId: '1:130994604981:web:ab0af3960a3ceb34c4a7fc',
    messagingSenderId: '130994604981',
    projectId: 'tv-ads-bf45e',
    authDomain: 'tv-ads-bf45e.firebaseapp.com',
    storageBucket: 'tv-ads-bf45e.appspot.com',
    measurementId: 'G-Y5XJZ6WX7V',
  );
}
